[functions.phone-login]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.qpay-billing]
verify_jwt = false

[functions.delete-registration]
verify_jwt = true

[functions.admin-dashboard]
verify_jwt = true
