const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const elements={};let modal='',requestHold=null,fail=false;const scopes=[];
const records=Array.from({length:251},(_,i)=>({id:'p'+i,status:'posted',supplier_id:'supplier-a',amount:100,payment_date:'2026-10-05',note:i===0?'Барааны төлбөр':'',reference:'REF',invoice_id:null}));
const ctx={console,Intl,Date,setTimeout:()=>0,document:{head:{appendChild(){}},createElement:()=>({}),getElementById:id=>elements[id]||{classList:{add(){}}}},page:'payments',render(){},__nayadActiveStoreId:'store-a',__nayadState:{read:()=>({companies:[{supabase_supplier_id:'supplier-a',name:'Example',invoices:[]}]})},sheet(s){modal=s;},closeSheet(){},toast(s){ctx.message=s;}};
ctx.window=ctx;
ctx.nayadSupabase={from(table){const q={};return {select(){return this;},eq(k,v){q[k]=v;return this;},gte(){return this;},lte(){return this;},order(){return this;},in(k,v){q[k]=v;return this;},async range(a,b){scopes.push({...q,table,a});if(requestHold){const p=requestHold;requestHold=null;await p;}if(fail)return {error:{message:'offline'}};return {data:table==='payments'?records.slice(a,b+1):a===0&&q.payment_id.includes('p0')?[{payment_id:'p0',invoice_id:'i1',cash_amount:60,invoices:{invoice_no:'INV-1'}},{payment_id:'p0',invoice_id:'i2',cash_amount:40,invoices:{invoice_no:'INV-2'}}]:[]};}};}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../payment-statement.js'),'utf8'),ctx);
(async()=>{
 const api=ctx.NayadStatement;
 await api.reload();
 assert.match(api.html(),/251 гүйлгээ/,'must paginate past first page');
 assert.match(api.html(),/25,100/,'sum payments once, not once per allocation');
 assert.ok(scopes.filter(q=>q.table==='payments').every(q=>q.store_id==='store-a'));
 assert.ok(scopes.filter(q=>q.table==='payment_allocations').every(q=>q['payments.store_id']==='store-a'));
 const f={from:'2026-10-05',to:'2026-10-05',supplier:'supplier-a',min:'100',max:'100',note:'БАРАА',invoice:'inv-2'};
 const sample={...records[0],allocations:[{invoices:{invoice_no:'INV-2'}}]};
 assert.equal(api.filterRows([sample,{...sample,status:'reversed'},{...sample,supplier_id:'other'},{...sample,payment_date:'2026-10-04'}],f).length,1);
 assert.equal(api.filterRows([sample],{...f,min:'101'}).length,0);
 assert.equal(api.filterRows([sample],{...f,note:'missing'}).length,0);
 api.details('p0');assert.match(modal,/INV-1/);assert.match(modal,/INV-2/);
 for(const [id,value] of Object.entries({stMin:'500',stMax:'100',stNote:'',stInvoice:''}))elements[id]={value};
 api.apply();assert.match(ctx.message,/зөв/);
 api.clear();assert.equal(elements.stMin.value,'');
 let release;requestHold=new Promise(r=>release=r);const pending=api.reload();ctx.__nayadActiveStoreId='store-b';api.tabs();release();await pending;
 assert.doesNotMatch(api.html(),/25,100/,'late response from former store must be discarded');
 fail=true;await api.reload();assert.match(api.html(),/Хуулга ачаалж чадсангүй/);assert.doesNotMatch(api.html(),/Нийт төлсөн/,'failure must not present a false zero total');
 console.log('payment-statement: PASS — pagination, allocations, filters, errors and store isolation');
})().catch(e=>{console.error(e);process.exitCode=1;});
